@ProyectoAPISimple_HostAddress = http://localhost:5069

GET {{ProyectoAPISimple_HostAddress}}/ejemplo
Accept: application/json

###

POST {{ProyectoAPISimple_HostAddress}}/ejemplo
Content-Type: application/json

{
  "nombre": "Ana",
  "cantidad": 3
}

###
